[package]
name = "langcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rustc-hash = "1"
bstr = "1"
rayon = "1"
rayon-core = "1"